var body_data = [{
        name: 'sun',
        radius: 432700,
        surface_texture: 'surface_textures/sun.jpg',
        mesh: 0,
    }, {
        name: 'mercury',
        radius: 1515.9593,
        surface_texture: 'surface_textures/mercury/mercury.jpg',
        mesh: 0
    }, {
        name: 'venus',
        radius: 3760.41418,
        surface_texture: 'surface_textures/venus/venus.jpg',
        mesh: 0
    }, {
        name: 'earth',
        radius: 3959,
        surface_texture: 'surface_textures/earth/earth.jpg',
        mesh: 0
    }, {
        name: 'moon',
        radius: 1079.57031,
        surface_texture: 'surface_textures/earth/moon.jpg',
        mesh: 0
    }, {
        name: 'mars',
        radius: 2110.79794,
        surface_texture: 'surface_textures/mars/mars.jpg',
        mesh: 0
    }, {
        name: 'jupiter',
        radius: 43440.7,
        surface_texture: 'surface_textures/jupiter/jupiter.jpg',
        mesh: 0
    }, {
        name: 'io',
        radius: 1131,
        surface_texture: 'surface_textures/jupiter/io.jpg',
        mesh: 0
    }, {
        name: 'europa',
        radius: 969,
        surface_texture: 'surface_textures/jupiter/europa.jpg',
        mesh: 0
    }, {
        name: 'ganymede',
        radius: 1635,
        surface_texture: 'surface_textures/jupiter/ganymede.jpg',
        mesh: 0
    }, {
        name: 'callisto',
        radius: 1498,
        surface_texture: 'surface_textures/jupiter/callisto.jpg',
        mesh: 0
    }, {
        name: 'saturn',
        radius: 37448.799,
        surface_texture: 'surface_textures/saturn/saturn.jpg',
        mesh: 0
    },

    {
        name: 'mimas',
        radius: 123,
        surface_texture: 'surface_textures/saturn/mimas.jpg',
        mesh: 0
    }, {
        name: 'enceladus',
        radius: 157,
        surface_texture: 'surface_textures/saturn/enceladus.jpg',
        mesh: 0
    }, {
        name: 'tethys',
        radius: 335,
        surface_texture: 'surface_textures/saturn/tethys.jpg',
        mesh: 0
    }, {
        name: 'dione',
        radius: 700,
        surface_texture: 'surface_textures/saturn/dione.jpg',
        mesh: 0
    }, {
        name: 'rhea',
        radius: 475,
        surface_texture: 'surface_textures/saturn/rhea.jpg',
        mesh: 0
    }, {
        name: 'iapetus',
        radius: 456,
        surface_texture: 'surface_textures/saturn/iapetus.jpg',
        mesh: 0
    }, {
        name: 'titan',
        radius: 1601,
        surface_texture: 'surface_textures/saturn/titan.jpg',
        mesh: 0
    }, {
        name: 'uranus',
        radius: 15881.6263,
        surface_texture: 'surface_textures/uranus/uranus.jpg',
        mesh: 0
    }, {
        name: 'miranda',
        radius: 290,
        surface_texture: 'surface_textures/uranus/miranda.jpg',
        mesh: 0
    }, {
        name: 'ariel',
        radius: 359,
        surface_texture: 'surface_textures/uranus/ariel.jpg',
        mesh: 0
    }, {
        name: 'umbriel',
        radius: 362,
        surface_texture: 'surface_textures/uranus/umbriel.jpg',
        mesh: 0
    }, {
        name: 'titania',
        radius: 489,
        surface_texture: 'surface_textures/uranus/titania.jpg',
        mesh: 0
    }, {
        name: 'oberon',
        radius: 472,
        surface_texture: 'surface_textures/uranus/oberon.jpg',
        mesh: 0
    }, {
        name: 'neptune',
        radius: 15387,
        surface_texture: 'surface_textures/neptune/neptune.jpg',
        mesh: 0
    }, {
        name: 'triton',
        radius: 840,
        surface_texture: 'surface_textures/neptune/triton.jpg',
        mesh: 0
    }, {
        name: 'proteus',
        radius: 124,
        surface_texture: 'surface_textures/neptune/proteus.jpg',
        mesh: 0
    }, {
        name: 'nereid',
        radius: 105,
        surface_texture: 'surface_textures/neptune/nereid.jpg',
        mesh: 0
    }, {
        name: 'pluto',
        radius: 733,
        surface_texture: 'surface_textures/pluto/pluto.jpg',
        mesh: 0
    }, {
        name: 'charon',
        radius: 376,
        surface_texture: 'surface_textures/pluto/charon.jpg',
        mesh: 0
    }, {
        name: 'trappist-1',
        radius: 49280,
        surface_texture: 'surface_textures/trappist/trappist-1.jpg',
        mesh: 0
    }, {
        name: 'trappist-b',
        radius: 1.086 * 3959,
        surface_texture: 'surface_textures/trappist/trappist-b.jpg',
        mesh: 0
    }, {
        name: 'trappist-c',
        radius: 1.056 * 3959,
        surface_texture: 'surface_textures/trappist/trappist-c.jpg',
        mesh: 0
    }, {
        name: 'trappist-d',
        radius: 0.772 * 3959,
        surface_texture: 'surface_textures/trappist/trappist-d.jpg',
        mesh: 0
    }, {
        name: 'trappist-e',
        radius: 0.918 * 3959,
        surface_texture: 'surface_textures/trappist/trappist-e.jpg',
        mesh: 0
    }, {
        name: 'trappist-f',
        radius: 1.045 * 3959,
        surface_texture: 'surface_textures/trappist/trappist-f.jpg',
        mesh: 0
    }, {
        name: 'trappist-g',
        radius: 1.127 * 3959,
        surface_texture: 'surface_textures/trappist/trappist-g.jpg',
        mesh: 0
    }, {
        name: 'trappist-h',
        radius: 0.755 * 3959,
        surface_texture: 'surface_textures/trappist/trappist-h.jpg',
        mesh: 0
    }
];
